project_name: mq-lease-service
version: 2

builds:
  - id: mq-lease-service
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - arm64
    - amd64
    binary: mq-lease-service
    main: ./cmd

kos:
- repositories:
  - ghcr.io/ankorstore/mq-lease-service
  main: ./cmd
  platforms:
  - linux/amd64
  - linux/arm64
  ldflags:
  - "-s -w -X github.com/ankorstore/mq-lease-service/internal/version.tag={{.Version}}"
  bare: true
  tags:
  - latest
  - '{{.Tag}}'
  - '{{if not .Prerelease}}stable{{end}}'
