project_name: mq-lease-service

kos:
- repository: ghcr.io/ankorstore/mq-lease-service
  main: ./cmd/
  platforms:
  - linux/amd64
  - linux/arm64
  ldflags:
  - "-s -w -X github.com/ankorstore/mq-lease-service/internal/version.tag={{.Version}}"
  bare: true
  tags:
  - latest
  - '{{.Tag}}'
  - '{{if not .Prerelease}}stable{{end}}'
