repos:
  - repo: git@github.com:ankorstore/pre-commit.git
    rev: e1b70866e5804334d8434d1dde92a558783761ff
    hooks:
      - id: required

  - repo: local
    hooks:
      - id: go-test
        name: go test
        language: system
        entry: make test
        types: [go]
        pass_filenames: false
      - id: go-e2e
        name: go e2e
        language: system
        entry: make e2e
        types: [ go ]
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: make lint
        types: [go]
        language: golang
        pass_filenames: false
      - id: gen-workflows
        name: gen-workflows
        entry: ./hack/gen_workflows.sh
        language: script
        pass_filenames: false
